#!/bin/sh

# Aktuelle hbci-version
ssh limoia.com 'cd /home/git; echo $[`cat hbci-version` + 1] > hbci-version.neu; mv hbci-version.neu hbci-version; cat hbci-version' \
    > hbci-version

# Bauen
cd src
/Developer_3/usr/bin/xcodebuild -project hbci.xcodeproj -target hbcimenu -configuration Release clean
/Developer_3/usr/bin/xcodebuild -project hbci.xcodeproj -target hbcimenu -configuration Release
/Developer_3/usr/bin/xcodebuild -project hbci.xcodeproj -target hbcimenu -configuration Release-growl-installer clean
/Developer_3/usr/bin/xcodebuild -project hbci.xcodeproj -target hbcimenu -configuration Release-growl-installer
cd ..
