#!/bin/sh

# Aktuelle hbci-version
ssh limoia.com 'cd /home/git; echo $[`cat hbci-version` + 1] > hbci-version.neu; mv hbci-version.neu hbci-version; cat hbci-version' \
    > hbci-version

# Bauen
cd src
xcodebuild -project hbci.xcodeproj -target hbcimenu -configuration Release clean
xcodebuild -project hbci.xcodeproj -target hbcimenu -configuration Release
cd ..
