#!/bin/sh

OLD_VERSION=$(cat hbci-version)
echo $[$OLD_VERSION + 1] > hbci-version

# Bauen
cd src
xcodebuild -project hbci.xcodeproj -target hbcimenu -configuration Release clean
xcodebuild -project hbci.xcodeproj -target hbcimenu -configuration Release
cd ..
