#!/bin/sh
(if [ -e .svn ]; then
    svn log --incremental -r $1:head
else
    HEAD=`git-svn info | grep "Revision:" | sed 's/[^0-9]*//'`
    git-svn log --revision=$1:$HEAD --incremental
fi) | grep -v line | grep -v '\-\-\-\-\-' | grep -v "^$" | sed 's#^\* *\(.*\)$#<li>\1</li>#'
